### PR TITLE
[TCL30-48] Bug: Fix Map Drag

### PR DESCRIPTION
**Pull request by jssckbl**
## Description

Observed:

- When the user shares their location, if they subsequently drag the map, the app automatically re-centers on the user’s location after a short period of time, usually between 5 to 45 seconds.

Expected:

- When the user shares their location, if they subsequently drag the map, the app stays at the new center until the user changes it.

## Related Issue

Closes [TCL30-48](https://the-collab-lab.atlassian.net/browse/TCL30-48) 

Also helps close Epic [TCL30-3](https://the-collab-lab.atlassian.net/browse/TCL30-3)

## Acceptance Criteria

User enables `Share location`

Pin showing user location appears

When user walks around, the pin should move with the user's movement

When user is standing still and drags the map, the last map view dragged to should persist until one of two things happen: 
- User clicks `Fly to me` button, or
- User drags map to new view

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

User clicks `Share location` button, map moves to where user is located.

https://user-images.githubusercontent.com/38255956/128764550-3131fa51-3e3a-4d26-b501-f2c0a29e15a4.mov

(The middle of the waiting period was trimmed out because it would have been 45 seconds of seeing nothing happen)

After user has remained at the same view that they dragged the map to, the app will eventually re-center to where the user is currently located, without a prompt from the user to do so.

https://user-images.githubusercontent.com/38255956/128764677-f6683b60-7a8c-4331-9934-22c3936c3bff.mov

### After

Expected action happens in that the map remains where the user drags the map to, despite where the user is actually located. This persists until the user again moves the map, or clicks the `Fly to me` button.

## Testing Steps / QA Criteria

1. Clone repository: `git clone https://github.com/the-collab-lab/tcl-30-whats-near-me`.
2. Change to PR branch: `git checkout jw-ac-fix-drag-map`
3. Install NPM dependencies: `npm install`.
4. Run dev server: `npm run start`
5. Open your browser: `http://localhost:3000/`
6. Click on the "Share my location" button, our map should change its center where you are.
7. Drag the map, wait for 5 or 45 sec, and it shouldn't happen anything (as a re-center our map).
8. Click on the "Fly to me" button, and you should come back to your current position if you share your location. Return to step 7. Again, it shouldn't happen anything.

### CODE REVIEW

**Review by meganmckissack — APPROVED** [review]
I tested the production link and the dragging without refreshing the map is working.   Interesting, looks like we had a use for the useRef hook after all.  I'm posting the article we referenced previously for everyone. [https://www.smashingmagazine.com/2020/07/custom-react-hook-fetch-cache-data/](https://www.smashingmagazine.com/2020/07/custom-react-hook-fetch-cache-data/)

**Review by katia-utochkina — COMMENTED** [review]
Looks great, very well done 💯. Thank you, @jssckbl and @alxmcr,  for fixing the bug

**Comment by alxmcr** [comment]
>  Looks great, very well done 💯. Thank you, @jssckbl and @alxmcr, for fixing the bug

Thanks, @katia-utochkina! If you don't mind, you can give us your approval in your review ✔️ , please!

**Review by katia-utochkina — APPROVED** [review]

**Comment by laurenmbeatty** [comment]
> I tested the production link and the dragging without refreshing the map is working. Interesting, looks like we had a use for the useRef hook after all. I'm posting the article we referenced previously for everyone. https://www.smashingmagazine.com/2020/07/custom-react-hook-fetch-cache-data/

Yes...very cool!  I approve as well. Can you all wait to merge until @katia-utochkina and @meganmckissack 's PR is merged? I think you're going to have to do a little bit of merge work to combine them. 👍

**Review by laurenmbeatty — APPROVED** [review]
LGTM 👍

**Comment by meganmckissack** [comment]
Ok, we've merged ours, let me know if you have any issues.

**Comment by alxmcr** [comment]
We are trying to solve some production issues.

**Pull request merged**
